[Config]
LOX_IP = 
LOX_PORT = 12340
LB_IP = <IP_ADDRESS_OF_DOCKER_CONTAINER>
LINK_ADR = 
LBU_PORT = <PORT_OF_DOCKER_CONTAINER>
LBH_PORT = <PORT_OF_DOCKER_CONTAINER>
LOX_TIME = False
USE_METRIC = True
IGNORE_EMPTY = True
UDP_ENABLE = False
UDP_ONCHANGE = True
UDP_IGNORE = 
UDP_MAXLEN = 
UDP_STATRESEND = 0
LANGUAGE = EN
AUTH_PWD = 
DEF_SID = 
REBOOT_ENABLE = False
RESTART_ENABLE = False
DT_FORMAT = %d.%m.%Y %H:%M:%S
RUN_DESC = 
USER_AGENT = "foshkplugin/0.0.10Beta"

[Weatherstation]
WS_IP = <IP_ADDRESS_OF_WEATHERSTATION>
WS_PORT = <PORT_OF_WEATHERSTATION>
WS_INTERVAL = 60
WS90_CONVERT = True
SNOW_DEPTH = 

[IoT]
IOT_ENABLE = True
IOT_INTERVAL = 10

[Export]
EVAL_VALUES = True
ADD_ITEMS = 
ADD_REMAP = 
ADD_DEWPT = True
ADD_SPREAD = True
ADD_VPD = True
ADD_SIGNAL = True
ADD_RSSI = True
ADD_RSSILVL = True
ADD_MORE = True
OUT_TEMP = 
OUT_HUM = 
OUT_TIME = False
FIX_LIGHTNING = True
UDP_MINMAX = True
URL_REPAIR = True
LIMIT_WINDGUST = 
ADD_SCRIPT = 
ADD_SUNDATA = True

[Forward]
FWD_ENABLE = False
FWD_CMT = This is a permanent comment field for notes on this forward
FWD_URL = 
FWD_INTERVAL = 
FWD_IGNORE = 
FWD_TYPE = 
FWD_OPTION = 
FWD_SID = 
FWD_PWD = 
FWD_REMAP = 
FWD_STATUS = False
FWD_MQTTCYCLE = 0
FWD_EXEC = 
FWD_WARNINT = 10
FWD_QUEUE = 
FWD_QDIR = 

[Forward-1]
FWD_ENABLE = True
FWD_CMT = MQTT
FWD_URL = <MQTT_BROKER_IP>:<MQTT_BROKER_PORT>@<MQTT_TOPIC>/<DEVICE_NAME>
FWD_INTERVAL = 60
FWD_IGNORE = 
FWD_TYPE = MQTTMET
FWD_OPTION = MQTTCYCLE=1,hass=True,devname=ecowitt-GW3000A,minmax=False,status=True,dtime_format="%d.%m.%Y %H:%M:%S",diagnostic=False
FWD_SID = meteo
FWD_PWD = meteo
FWD_REMAP = 
FWD_STATUS = True
FWD_MQTTCYCLE = 0
FWD_EXEC = 
FWD_WARNINT = 10
FWD_QUEUE = 
FWD_QDIR = 

[Forward-2]
FWD_CMT = Windy.com
FWD_ENABLE = True
FWD_TYPE = WINDY
FWD_SID = 0GzZW7bF
FWD_PWD = <API_KEY_FROM_WINDY_DASHBOARD>
FWD_URL = https://stations.windy.com/api/v2/observation/update
FWD_INTERVAL = 60

[Forward-3]
FWD_CMT = HASS
FWD_ENABLE = True
FWD_TYPE = EW
FWD_URL = http://<IP_ADDRESS_OF_HASS>/api/webhook/<WEBHOOK_ID>
FWD_INTERVAL = 60

[Forward-4]
FWD_CMT = ECOWITT2MQTT
FWD_ENABLE = True
FWD_TYPE = RAWEW
FWD_URL = http://<IP_ADDRESS_OF_ECOWITT2MQTT_DOCKER_CONTAINER>:<PORT_OF_ECOWITT2MQTT_DOCKER_CONTAINER>/data/report
FWD_INTERVAL = 60

[CSV]
CSV_NAME = 
CSV_FIELDS = 
CSV_INTERVAL = 
CSV_DAYFILE = 

[Warning]
WSDOG_WARNING = True
WSDOG_INTERVAL = 3
WSDOG_RESTART = 0
SENSOR_WARNING = False
SENSOR_MANDATORY = wh90cap_volt
BATTERY_WARNING = True
BATTERY_WARNEXCLUDE = 
STORM_WARNING = True
STORM_WARNDIFF = 1.75
STORM_WARNDIFF3H = 3.75
STORM_EXPIRE = 60
TSTORM_WARNING = True
TSTORM_WARNCOUNT = 1
TSTORM_WARNDIST = 30
TSTORM_EXPIRE = 15
LEAKAGE_WARNING = False
CO2_WARNING = False
CO2_WARNLEVEL = 1000
CO2_WARNKEY = 
INTVL_WARNING = False
INTVL_PCT = 10
REBOOT_WARNING = True
FWD_WARNING = True
FWD_WARNINT = 10

[Logging]
LOG_ENABLE = True
LOG_LEVEL = ALL
IGNORE_LOG = 
BUT_PRINT = True
COLOR_PRINT = True
logfile = /opt/foshkplugin/logs/log-foshkplugin.log
rawfile = /opt/foshkplugin/logs/raw-foshkplugin.log
sndfile = /opt/foshkplugin/logs/snd-foshkplugin.log

[Update]
UPD_CHECK = True
UPD_INTERVAL = 86400

[Pushover]
PO_ENABLE = True
PO_URL = 
PO_TOKEN = <PO_TOKEN>
PO_USER = <PO_USER>
PO_CUSTOMWARNING = False
PO_CUSTOM = @tempc <= 2.5,Current temperature (@value°C) is equal or below 2.5°C!,False,3600
PO_CUSTOM1 = @tempf < 32,Current temperature (@value°F) is below 32°F!,False,3600

[Coordinates]
ALT = <ALTITUDE_IN_METERS>
LAT = <LATITUDE>
LON = <LONGITUDE>

[Sunduration]
SUN_CALC = True
SUN_MIN = 12
SUN_COEF = 0.92
SUNSHINE_HOLD = 0
